name: CSSE_23_24

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - pandas
  - tensorflow =2.14.0  #Needed for session 02, my demo.
  - python >=3.7,<4.0
  - gitpython
  - matplotlib
  - scipy