name: CSSE_23_24

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - pandas
  - tensorflow
  - scikit-learn
  - keras
  - python >=3.7,<4.0
  - gitpython
  - matplotlib
  - pip
  - scipy
  - pydot
  - ipympl
  - pip:
    - pystan